[ch_2]
# Source information
name = "Weathernews"
source = "https://movie.mcas.jp/mcas/smil:wn1.smil/chunklist_b1800000.m3u8"

# Channel information
master_channel = 2
virtual_channel = 1

# Frequency information
freq_type = "8vsb" # qam256/qam64 for cable, 8vsb for antenna

# Signal information
signal_strength = 100
signal_quality = 100
symbol_quality = 100
